site_name: Ingredients

theme:
  name: material

watch:
  - src
  - tests

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

nav:
  - index.md
  - db.md
  - repository.md
